language: node_js
node_js:
- '11'
before_install:
- openssl aes-256-cbc -K $encrypted_d657022b50e5_key -iv $encrypted_d657022b50e5_iv
  -in id_rsa.enc -out id_rsa -d
- npm install -g discord.js
- npm install -g readline
- npm install -g facebook-chat-api
- npm install ts-node@3.2.0 --save
- npm install @types/node
- npm install -g typescript

install:
- npm install
- tsc -p tsconfig.json
script:
- npm install
after_success:
- npm install typedoc --global
- typedoc --out ./ ./bin/
- bash ".travis/deploy.sh"
